version: "3.8"

services:
  nodeserver:
    platform: linux/x86_64
    build:
      context: ./
    ports:
      - "8000:8000"
  nginx:
    restart: always
    build:
      context: ./nginx
    ports:
      - "3000:80"
